version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
    env_file:
      - .env
    restart: unless-stopped

  # Local development with Firestore emulator
  firestore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8080:8080"
    profiles:
      - dev
